linkPhotoset: https://www.google.com
linkSource: https://github.com/baobabKoodaa/gatsby-starter-photo-book
linkPhotographer: https://www.freelancephotographer.co.za/
linkVenue: http://weddingsbycw.co.za/